// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * キャラクタを表す構造体
 */
export type Character = { 
/**
 * キャラクターID
 */
id: number, 
/**
 * 名前
 */
name: string, 
/**
 * 説明
 */
description: string, 
/**
 * 必須メディア
 */
necessary_media: NecessaryMedia, 
/**
 * 追加メディア
 */
optional_media: OptionalMedia, 
/**
 * サムネイル画像のパス
 */
thumbnail_source: MediaSource, 
/**
 * セリフ
 */
dialogues: Dialogue, 
/**
 * アプリ標準かユーザー作成か
 */
is_standard: boolean, 
/**
 * 作者
 */
author: string | null, };

export type Dialogue = { usual: string | null, addition: string | null, achievement: string | null, on_stage: string | null, off_stage: string | null, touch: string | null, };

export type MediaSource = { "Embedded": string } | { "External": string };

export type NecessaryMedia = { 
/**
 * 通常時メディア
 */
usual: MediaSource, 
/**
 * 追加時メディア
 */
addition: MediaSource, 
/**
 * 達成時メディア
 */
achievement: MediaSource, 
/**
 * 登場時メディア
 */
on_stage: MediaSource, };

export type OptionalMedia = { 
/**
 * 退場時メディア
 */
off_stage: MediaSource | null, 
/**
 * タッチ時メディア
 */
touch: MediaSource | null, };
