// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Animation = { 
/**
 * アニメーションファイルのパス
 */
path: string, 
/**
 * アニメーションの種類
 */
kind: AnimationKind, };

export type AnimationKind = "Image" | "Movie";

/**
 * キャラクタを表す構造体
 */
export type Character = { 
/**
 * キャラクターID
 */
id: number, 
/**
 * 名前
 */
name: string, 
/**
 * 説明
 */
description: string, 
/**
 * 必須アニメーション
 */
necessary_animation: NecessaryAnimation, 
/**
 * 追加アニメーション
 */
optional_animations: OptionalAnimation, 
/**
 * セリフ
 */
dialogues: Dialogue, 
/**
 * 作者
 */
author: string | null, };

export type Dialogue = { usual: string | null, addition: string | null, achievement: string | null, on_stage: string | null, off_stage: string | null, touch: string | null, };

export type NecessaryAnimation = { 
/**
 * 通常時アニメーション
 */
usual: Animation, 
/**
 * 追加時アニメーション
 */
addition: Animation, 
/**
 * 達成時アニメーション
 */
achievement: Animation, 
/**
 * 登場時アニメーション
 */
on_stage: Animation, };

export type OptionalAnimation = { 
/**
 * 退場時アニメーション
 */
off_stage: Animation | null, 
/**
 * タッチ時アニメーション
 */
touch: Animation | null, };
