// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * アドオンの種類
 */
export type AddonType = "DataExpansion" | "MotionExpansion" | "CustomFrameAdd1" | "CustomFrameAdd2" | "CustomFrameAdd4";
