// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Importance = "Unimportant" | "Normal" | "Important" | "Crucial";

export type Status = "ToDo" | "Waiting" | "WantDo" | "Doing";

/**
 * タスクを表す構造体
 */
export type Task = { 
/**
 * タスクID
 */
id: number, 
/**
 * タイトル
 */
title: string, 
/**
 * 説明
 */
description: string, 
/**
 * 締め切り日
 */
due_date: string | null, 
/**
 * 作成日
 */
created_date: string, 
/**
 * 提案から外れた日
 */
out_cast_date: string | null, 
/**
 * 重要度
 */
importance: Importance, 
/**
 * ステータス
 */
status: Status, 
/**
 * 表示順
 */
display_order: number, };
