// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * ユーザーを表す構造体
 */
export type User = { 
/**
 * ユーザーID
 */
id: number, 
/**
 * 使用中キャラクターID
 */
current_character_id: number, };
