// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Language = "ja" | "en" | "Other";

/**
 * ユーザーを表す構造体
 */
export type User = { 
/**
 * 管理番号、ユーザが複数人いる場合、拡張性要件より
 */
id: number, 
/**
 * 使用中キャラクターID
 */
current_character_id: number, 
/**
 * 言語
 */
language: Language, };
