// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UserError = { "type": "ParseError", "message": string } | { "type": "ValidationError", "message": string } | { "type": "IoError", "message": string } | { "type": "NotFoundError", "message": string } | { "type": "PoisonError", "message": string } | { "type": "StoreError", "message": string };
